### ISSUE TITLE
NPE in AdvancedInventoryRelay

### ISSUE THREAD

**Issue by peddermaster2** [Vswe/ModJam3#39]
This NPE is thrown when a player click on "Give Permission". The player is then dropped with the "Internal Server Error".
The same happens when a player clicks on "Active" for a player.

Version: A46
Direwolf20 Pack 1.0.14

```
java.lang.NullPointerException
    at vswe.stevesfactory.blocks.TileEntityRelay.func_70296_d(TileEntityRelay.java:418)
    at vswe.stevesfactory.network.PacketHandler.onPacketData(PacketHandler.java:46)
    at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:255)
    at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:245)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:85)
    at net.minecraft.network.NetServerHandler.func_72501_a(NetServerHandler.java:1130)
    at net.minecraft.network.packet.Packet250CustomPayload.func_73279_a(SourceFile:61)
    at net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:462)
    at net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:141)
    at net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
    at net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:691)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:276)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

**Comment by Vswe** [comment]
I found this bug myself just now, then I saw your report. I'll push a fix (for now, place a chest where the relay is facing while editing).
