### ISSUE TITLE
Crash when opening the inventory tab in the output/input tabs.

### ISSUE THREAD

**Issue by luckcolors** [Vswe/ModJam3#78]
this is from the solitary craft modpack here's the log:
(i've cutted where the bug starts)

[16/11/2014 20:16:25 PM] [Client thread/INFO] [inventorytweaks]: vswe.stevesfactory.interfaces.GuiManager
[16/11/2014 20:16:34 PM] Nov 16, 2014 8:16:34 PM net.techbrew.journeymap.JourneyMap stopMapping
[16/11/2014 20:16:34 PM] INFO: Mapping halting in Server di Minecraft dimension 0.
[16/11/2014 20:16:34 PM] [Client thread/INFO] [FML]: Applying holder lookups
[16/11/2014 20:16:34 PM] [Client thread/INFO] [FML]: Holder lookups applied
[16/11/2014 20:16:37 PM] [20:16:37] [Client thread/FATAL]: Reported exception thrown!
[16/11/2014 20:16:37 PM] net.minecraft.util.ReportedException: Rendering screen
[16/11/2014 20:16:37 PM]    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1092) ~[blt.class:?]
[16/11/2014 20:16:37 PM]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990) ~[bao.class:?]
[16/11/2014 20:16:37 PM]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[16/11/2014 20:16:37 PM]    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[16/11/2014 20:16:37 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_51]
[16/11/2014 20:16:37 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
[16/11/2014 20:16:37 PM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_51]
[16/11/2014 20:16:37 PM]    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_51]
[16/11/2014 20:16:37 PM]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
[16/11/2014 20:16:37 PM]    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[16/11/2014 20:16:37 PM] Caused by: java.lang.NullPointerException
[16/11/2014 20:16:37 PM]    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215) ~[add.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawItemStack(GuiBase.java:366) ~[GuiBase.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawBlock(GuiBase.java:263) ~[GuiBase.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.blocks.ConnectionBlock.draw(ConnectionBlock.java:65) ~[ConnectionBlock.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.drawContainer(ComponentMenuContainer.java:446) ~[ComponentMenuContainer.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:172) ~[ComponentMenuContainer$2.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:108) ~[ComponentMenuContainer$2.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ScrollController.draw(ScrollController.java:195) ~[ScrollController.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.draw(ComponentMenuContainer.java:495) ~[ComponentMenuContainer.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.FlowComponent.draw(FlowComponent.java:257) ~[FlowComponent.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiManager.drawGuiContainerBackgroundLayer(GuiManager.java:136) ~[GuiManager.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiAntiNEI.func_73863_a(GuiAntiNEI.java:73) ~[GuiAntiNEI.class:?]
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.func_73863_a(GuiBase.java:450) ~[GuiBase.class:?]
[16/11/2014 20:16:37 PM]    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) ~[blt.class:?]
[16/11/2014 20:16:37 PM]    ... 9 more
[16/11/2014 20:16:37 PM] ---- Minecraft Crash Report ----
[16/11/2014 20:16:37 PM] // Ooh. Shiny.
[16/11/2014 20:16:37 PM] 
[16/11/2014 20:16:37 PM] Time: 11/16/14 8:16 PM
[16/11/2014 20:16:37 PM] Description: Rendering screen
[16/11/2014 20:16:37 PM] 
[16/11/2014 20:16:37 PM] java.lang.NullPointerException: Rendering screen
[16/11/2014 20:16:37 PM]    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawItemStack(GuiBase.java:366)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawBlock(GuiBase.java:263)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.blocks.ConnectionBlock.draw(ConnectionBlock.java:65)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.drawContainer(ComponentMenuContainer.java:446)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:172)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:108)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ScrollController.draw(ScrollController.java:195)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.draw(ComponentMenuContainer.java:495)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.components.FlowComponent.draw(FlowComponent.java:257)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiManager.drawGuiContainerBackgroundLayer(GuiManager.java:136)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiAntiNEI.func_73863_a(GuiAntiNEI.java:73)
[16/11/2014 20:16:37 PM]    at vswe.stevesfactory.interfaces.GuiBase.func_73863_a(GuiBase.java:450)
[16/11/2014 20:16:37 PM]    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[16/11/2014 20:16:38 PM]    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[16/11/2014 20:16:38 PM]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[16/11/2014 20:16:38 PM]    at net.minecraft.client.main.Main.main(SourceFile:148)
[16/11/2014 20:16:38 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16/11/2014 20:16:38 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16/11/2014 20:16:38 PM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16/11/2014 20:16:38 PM]    at java.lang.reflect.Method.invoke(Unknown Source)
[16/11/2014 20:16:38 PM]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
[16/11/2014 20:16:38 PM]    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16/11/2014 20:16:38 PM] 
[16/11/2014 20:16:38 PM] 
[16/11/2014 20:16:38 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[16/11/2014 20:16:38 PM] ---------------------------------------------------------------------------------------
[16/11/2014 20:16:38 PM] 
[16/11/2014 20:16:38 PM] -- Head --
[16/11/2014 20:16:38 PM] Stacktrace:
[16/11/2014 20:16:38 PM]    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:215)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawItemStack(GuiBase.java:366)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.interfaces.GuiBase.drawBlock(GuiBase.java:263)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.blocks.ConnectionBlock.draw(ConnectionBlock.java:65)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.drawContainer(ComponentMenuContainer.java:446)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:172)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.ComponentMenuContainer$2.draw(ComponentMenuContainer.java:108)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.ScrollController.draw(ScrollController.java:195)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.ComponentMenuContainer.draw(ComponentMenuContainer.java:495)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.components.FlowComponent.draw(FlowComponent.java:257)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.interfaces.GuiManager.drawGuiContainerBackgroundLayer(GuiManager.java:136)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.interfaces.GuiAntiNEI.func_73863_a(GuiAntiNEI.java:73)
[16/11/2014 20:16:38 PM]    at vswe.stevesfactory.interfaces.GuiBase.func_73863_a(GuiBase.java:450)
[16/11/2014 20:16:38 PM] 
[16/11/2014 20:16:38 PM] -- Screen render details --
[16/11/2014 20:16:38 PM] Details:
[16/11/2014 20:16:38 PM]    Screen name: vswe.stevesfactory.interfaces.GuiManager
[16/11/2014 20:16:38 PM]    Mouse location: Scaled: (144, 85). Absolute: (288, 308)
[16/11/2014 20:16:38 PM]    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
[16/11/2014 20:16:38 PM] 
[16/11/2014 20:16:38 PM] -- Affected level --
[16/11/2014 20:16:38 PM] Details:
[16/11/2014 20:16:38 PM]    Level name: MpServer
[16/11/2014 20:16:38 PM]    All players: 1 total; [EntityClientPlayerMP['**MINECRAFTUSERNAME**'/1450094, l='MpServer', x=-42.70, y=70.62, z=144.91]]
[16/11/2014 20:16:38 PM]    Chunk stats: MultiplayerChunkCache: 441, 441
[16/11/2014 20:16:38 PM]    Level seed: 0
[16/11/2014 20:16:38 PM]    Level generator: ID 00 - default, ver 1. Features enabled: false
[16/11/2014 20:16:38 PM]    Level generator options: 
[16/11/2014 20:16:38 PM]    Level spawn location: World: (-7,64,222), Chunk: (at 9,4,14 in -1,13; contains blocks -16,0,208 to -1,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
[16/11/2014 20:16:38 PM]    Level time: 15764176 game time, 599421 day time
[16/11/2014 20:16:38 PM]    Level dimension: 0
[16/11/2014 20:16:39 PM]    Level storage version: 0x00000 - Unknown?
[16/11/2014 20:16:39 PM]    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[16/11/2014 20:16:39 PM]    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
[16/11/2014 20:16:39 PM]    Forced entities: 97 total; [EntitySkeleton['Scheletro'/1450753, l='MpServer', x=-120.50, y=18.00, z=78.50], EntityItem['item.item.egg'/1450037, l='MpServer', x=9.78, y=80.13, z=150.13], EntityChicken['Pollo'/9, l='MpServer', x=27.84, y=72.95, z=93.03], EntityCreeper['Creeper'/1450286, l='MpServer', x=-51.47, y=77.00, z=130.00], EntitySkeleton['Scheletro'/1450760, l='MpServer', x=2.50, y=27.00, z=143.50], EntityCreeper['Creeper'/1450285, l='MpServer', x=-46.75, y=78.00, z=127.13], EntityItem['item.item.string'/1450040, l='MpServer', x=-32.81, y=57.13, z=162.38], EntitySkeleton['Scheletro'/1450041, l='MpServer', x=-22.50, y=67.00, z=211.50], EntityZombie['Zombi'/538979, l='MpServer', x=-86.03, y=14.00, z=221.50], EntityItem['item.item.bone'/1450043, l='MpServer', x=-49.88, y=26.13, z=194.81], EntityClientPlayerMP['**MINECRAFTUSERNAME**'/1450094, l='MpServer', x=-42.70, y=70.62, z=144.91], EntityItem['item.item.egg'/1449893, l='MpServer', x=-1.38, y=79.13, z=99.16], EntityItem['item.item.egg'/1450302, l='MpServer', x=-101.63, y=65.13, z=158.56], EntityZombie['Zombi'/1450300, l='MpServer', x=11.50, y=64.00, z=187.50], EntityZombie['Zombi'/766146, l='MpServer', x=-50.53, y=23.00, z=189.97], EntityZombie['Zombi'/1236818, l='MpServer', x=-76.31, y=16.00, z=202.88], EntityEnderman['Enderman'/1450793, l='MpServer', x=-88.50, y=42.00, z=76.50], EntityEnderman['Enderman'/1450792, l='MpServer', x=-87.66, y=42.00, z=76.50], EntityBat['Pipistrello'/1450557, l='MpServer', x=-122.47, y=24.10, z=205.72], EntitySkeleton['Scheletro'/1449861, l='MpServer', x=28.50, y=53.00, z=76.50], EntitySheep['Pecora'/63, l='MpServer', x=-119.53, y=64.00, z=205.66], EntityPig['Maiale'/62, l='MpServer', x=-119.41, y=64.00, z=178.31], EntitySlime['Gelatina'/1185139, l='MpServer', x=-24.69, y=13.00, z=142.69], EntityXPOrb['Sfera d'esperienza'/1450096, l='MpServer', x=-29.38, y=78.25, z=95.31], EntitySlime['Gelatina'/1129718, l='MpServer', x=-16.63, y=9.00, z=134.38], EntityZombie['Zombi'/963581, l='MpServer', x=-105.30, y=15.00, z=123.30], EntityItem['item.item.egg'/1447785, l='MpServer', x=-98.22, y=64.13, z=156.19], EntityBat['Pipistrello'/1450576, l='MpServer', x=-26.25, y=12.10, z=165.31], EntitySkeleton['Scheletro'/1447776, l='MpServer', x=-61.50, y=44.00, z=221.50], EntityCreeper['Creeper'/1450109, l='MpServer', x=-16.50, y=77.00, z=67.50], EntityPig['Maiale'/85, l='MpServer', x=-102.13, y=64.00, z=166.31], EntityChicken['Pollo'/84, l='MpServer', x=-115.84, y=64.00, z=168.69], EntityBat['Pipistrello'/1450356, l='MpServer', x=-52.63, y=35.00, z=196.47], EntityPig['Maiale'/93, l='MpServer', x=-74.88, y=65.00, z=194.19], EntityPig['Maiale'/92, l='MpServer', x=-107.91, y=64.00, z=191.50], EntityChicken['Pollo'/94, l='MpServer', x=-100.84, y=62.20, z=188.47], EntitySheep['Pecora'/89, l='MpServer', x=-111.38, y=64.00, z=188.50], EntityPig['Maiale'/88, l='MpServer', x=-103.34, y=66.00, z=160.44], EntityChicken['Pollo'/1450095, l='MpServer', x=-43.56, y=72.00, z=76.69], EntityPig['Maiale'/91, l='MpServer', x=-111.28, y=64.00, z=198.91], EntitySheep['Pecora'/90, l='MpServer', x=-93.66, y=66.00, z=202.69], EntityItem['item.item.string'/1450307, l='MpServer', x=-35.69, y=57.13, z=171.59], EntityBat['Pipistrello'/1450609, l='MpServer', x=-66.16, y=30.89, z=207.44], EntityBat['Pipistrello'/1450610, l='MpServer', x=-46.16, y=40.10, z=190.78], EntityChicken['Pollo'/110, l='MpServer', x=-100.94, y=64.00, z=156.38], EntityChicken['Pollo'/109, l='MpServer', x=-102.47, y=66.00, z=160.38], EntityChicken['Pollo'/106, l='MpServer', x=-88.56, y=69.00, z=104.59], EntityChicken['Pollo'/104, l='MpServer', x=-88.34, y=68.00, z=102.56], EntitySpider['Ragno'/1451023, l='MpServer', x=-27.50, y=26.00, z=184.50], EntityItem['item.item.egg'/1448841, l='MpServer', x=-100.88, y=62.13, z=187.69], EntityPig['Maiale'/114, l='MpServer', x=-92.47, y=66.00, z=200.09], EntityPig['Maiale'/113, l='MpServer', x=-95.56, y=64.00, z=191.47], EntityPig['Maiale'/112, l='MpServer', x=-93.84, y=65.00, z=171.44], EntityItem['item.item.feather'/1446205, l='MpServer', x=-99.03, y=64.13, z=156.38], EntityBat['Pipistrello'/1450605, l='MpServer', x=-36.63, y=40.00, z=190.22], EntityPig['Maiale'/126, l='MpServer', x=-76.94, y=64.00, z=183.91], EntityItem['item.item.string'/1450057, l='MpServer', x=-29.28, y=54.13, z=167.13], EntityItem['item.item.string'/1446650, l='MpServer', x=-1.84, y=31.13, z=99.88], EntityZombie['Zombi'/1270610, l='MpServer', x=-8.06, y=46.00, z=174.50], EntityBat['Pipistrello'/1448558, l='MpServer', x=-105.55, y=16.08, z=123.74], EntityPig['Maiale'/128, l='MpServer', x=-81.56, y=63.00, z=124.19], EntityItem['item.item.egg'/1447589, l='MpServer', x=-86.44, y=68.13, z=102.94], EntityPig['Maiale'/150, l='MpServer', x=-63.16, y=66.00, z=98.03], EntityItem['item.item.feather'/1446857, l='MpServer', x=-102.19, y=65.13, z=158.28], EntityItem['item.item.feather'/1446855, l='MpServer', x=-86.03, y=68.13, z=102.81], EntityItem['item.item.egg'/1451230, l='MpServer', x=8.16, y=78.13, z=142.13], EntitySkeleton['Scheletro'/1451206, l='MpServer', x=-110.50, y=17.00, z=143.50], EntityCreeper['Creeper'/1450668, l='MpServer', x=-26.97, y=75.00, z=85.59], EntitySkeleton['Scheletro'/1451207, l='MpServer', x=-109.50, y=17.00, z=142.50], EntitySkeleton['Scheletro'/1451204, l='MpServer', x=-107.50, y=17.00, z=141.50], EntitySkeleton['Scheletro'/1451205, l='MpServer', x=-107.50, y=17.00, z=142.50], EntitySlime['Gelatina'/1399793, l='MpServer', x=-11.31, y=11.00, z=128.31], EntitySheep['Pecora'/787265, l='MpServer', x=30.75, y=75.00, z=65.63], EntityZombie['Zombi'/690668, l='MpServer', x=-100.75, y=18.00, z=112.84], EntityZombie['Zombi'/206, l='MpServer', x=-7.30, y=11.39, z=161.30], EntityZombie['Zombi'/201, l='MpServer', x=-5.13, y=53.00, z=137.41], EntityChicken['Pollo'/200, l='MpServer', x=-2.34, y=79.00, z=98.38], EntityZombie['Zombi'/860494, l='MpServer', x=-45.50, y=21.00, z=152.31], EntityCreeper['Creeper'/1450477, l='MpServer', x=-66.84, y=63.00, z=75.22], EntityBat['Pipistrello'/1450950, l='MpServer', x=-118.44, y=24.12, z=201.75], EntityBat['Pipistrello'/1450951, l='MpServer', x=-116.06, y=25.00, z=201.41], EntityChicken['Pollo'/220, l='MpServer', x=11.50, y=77.00, z=148.50], EntitySlime['Gelatina'/1326137, l='MpServer', x=-9.31, y=13.00, z=147.69], EntityChicken['Pollo'/219, l='MpServer', x=9.50, y=77.00, z=145.50], EntitySlime['Gelatina'/1426214, l='MpServer', x=-48.69, y=6.00, z=141.69], EntitySpider['Ragno'/1437349, l='MpServer', x=-47.28, y=51.00, z=158.28], EntityCreeper['Creeper'/1450960, l='MpServer', x=-87.44, y=43.00, z=77.66], EntitySkeleton['Scheletro'/1450991, l='MpServer', x=33.50, y=26.00, z=153.50], EntityCreeper['Creeper'/1450748, l='MpServer', x=-60.50, y=28.00, z=215.50], EntityChicken['Pollo'/232, l='MpServer', x=-35.41, y=66.00, z=192.53], EntitySheep['Pecora'/231, l='MpServer', x=14.88, y=78.00, z=112.91], EntityBat['Pipistrello'/1448252, l='MpServer', x=-10.75, y=12.10, z=161.25], EntityChicken['Pollo'/228, l='MpServer', x=21.25, y=73.75, z=78.56], EntityBat['Pipistrello'/1449806, l='MpServer', x=-34.56, y=55.10, z=173.25], EntitySlime['Gelatina'/1160954, l='MpServer', x=-16.63, y=21.00, z=139.38], EntityZombie['Zombi'/1264356, l='MpServer', x=17.50, y=33.00, z=119.03], EntitySheep['Pecora'/245, l='MpServer', x=34.34, y=78.00, z=124.47]]
[16/11/2014 20:16:39 PM]    Retry entities: 0 total; []
[16/11/2014 20:16:39 PM]    Server brand: fml,forge
[16/11/2014 20:16:39 PM]    Server type: Non-integrated multiplayer server
[16/11/2014 20:16:39 PM] Stacktrace:
[16/11/2014 20:16:39 PM]    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
[16/11/2014 20:16:39 PM]    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
[16/11/2014 20:16:39 PM]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:908)
[16/11/2014 20:16:39 PM]    at net.minecraft.client.main.Main.main(SourceFile:148)
[16/11/2014 20:16:39 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16/11/2014 20:16:39 PM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16/11/2014 20:16:39 PM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16/11/2014 20:16:39 PM]    at java.lang.reflect.Method.invoke(Unknown Source)
[16/11/2014 20:16:39 PM]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
[16/11/2014 20:16:39 PM]    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16/11/2014 20:16:39 PM] 
[16/11/2014 20:16:39 PM] -- System Details --
[16/11/2014 20:16:39 PM] Details:
[16/11/2014 20:16:39 PM]    Minecraft Version: 1.7.10
[16/11/2014 20:16:39 PM]    Operating System: Windows 7 (amd64) version 6.1
[16/11/2014 20:16:39 PM]    Java Version: 1.7.0_51, Oracle Corporation
[16/11/2014 20:16:39 PM]    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[16/11/2014 20:16:39 PM]    Memory: 461324256 bytes (439 MB) / 1399279616 bytes (1334 MB) up to 2112618496 bytes (2014 MB)
[16/11/2014 20:16:39 PM]    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx2048M -XX:PermSize=512M
[16/11/2014 20:16:39 PM]    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[16/11/2014 20:16:39 PM]    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[16/11/2014 20:16:39 PM]    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 103 mods loaded, 103 mods active
[16/11/2014 20:16:39 PM]    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[16/11/2014 20:16:39 PM]    FML{7.10.25.1207} [Forge Mod Loader](forge-1.7.10-10.13.0.1207-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[16/11/2014 20:16:39 PM]    Forge{10.13.0.1207} [Minecraft Forge](forge-1.7.10-10.13.0.1207-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[16/11/2014 20:16:39 PM]    appliedenergistics2-core{rv1-beta-34} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
[16/11/2014 20:16:39 PM] #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\Instances\SolitaryCraft\crash-reports\crash-2014-11-16_20.16.37-client.txt 

I hope you could help me.
Thanks in advance.

**Comment by luckcolors** [comment]
The problem just fixed it self you can just checkout the log anyway :).
